spring.datasource.url=jdbc:mysql://mysql-141cce16-tuyen88931600-06e9.i.aivencloud.com:16229/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_93xSsxO8vWx0pBdcyg5

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
